import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/layout/Header";
import Body from "@/layout/body";
import MultiSigAddressContext from "@/globalContext";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [multiSigAddress, setMultiSigAddress] = useState(null);
  const [isAddressOwner, setAddressOwner] = useState(false);
  const [walletEthBalance, setWalletEthBalance] = useState(0);
  return (
    <>
      <Head>
        <title>MultiSig Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
          <MultiSigAddressContext.Provider
            value={{
              multiSigAddress,
              setMultiSigAddress,
              isAddressOwner,
              setAddressOwner,
              walletEthBalance,
              setWalletEthBalance,
            }}
          >
            <Header />
            <Body />
            {/* Head Section to be created */}
            {/* Body Section to be created */}
          </MultiSigAddressContext.Provider>
        </div>
      </main>
    </>
  );
}
